GET http://localhost:3000/api/products
//kollar alla mina produkter  
###


GET http://localhost:3000/api/products/2
//kolla bara en id
###


POST http://localhost:3000/api/products
Content-Type: application/json
//lägger till den producten

{
"id": 5,
"name": "Molgan",
"lastname": "Johansson",
"age": "20",
"längd": "120"
}
###


DELETE http://localhost:3000/api/products/5
//Ta bort en id
###


PUT http://localhost:3000/api/products/4
Content-Type: application/json
//här väljer jag vad jag vill uppdatera med hjälp av en id

{ 
"name": "uppdaterad",
"lastname": "uppdaterad1"
}
###