GET http://localhost:3000/api/products
//kollar alla mina produkter  
###


GET http://localhost:3000/api/products/2
//kolla bara en id
###


POST http://localhost:3000/api/products
Content-Type: application/json
//lägger till den producten

{
"id": 5,
"name": "Sony 4K QL smart TV",
"pris": "8990 Kr",
"storlek": "65 tum",
"år": "2021"
}
###


DELETE http://localhost:3000/api/products/5
//Ta bort en id
###


PUT http://localhost:3000/api/products/4
Content-Type: application/json
//här väljer jag vad jag vill uppdatera med hjälp av en id

{ 
"name": "Andersson 1K TV",
"pris": "1000 Kr",
"storlek": "10 tum"
}
###