GET http://localhost:3000/api/products
//kollar alla mina produkter  
###


GET http://localhost:3000/api/products/1
//kolla bara en id
###


POST http://localhost:3000/api/products/
//Lägg till en id
###


DELETE http://localhost:3000/api/products/1
//Ta bort en id
###

PUT http://localhost:3000/api/products/:id
//uppdatera in en id 
###